### ISSUE TITLE
This package is out-of-date

### ISSUE THREAD

**Issue by unknwon** [go-xorm/tidb#6]
Not able to compile with error:

```
go-xorm/tidb/tidb_dialect.go:151: cannot use make(map[string]bool) (type map[string]bool) as type map[string]int in assignment
```

**Comment by shenli** [comment]
@Unknwon @lunny We are going to remove TiDB driver soon. go-xorm could use mysql driver to access TiDB. I will update this repo.

**Comment by unknwon** [comment]
Forgot to close, fix the error yesterday... :trollface:

**Comment by lunny** [comment]
OK! @shenli
